name: Node-CI

on:
  push:
    branches: [ master, develop, TestNetwork ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[update]')"

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build

  deploy-prod:
    environment: production
    if: "github.ref == 'refs/heads/master'"
    runs-on: ubuntu-18.04
    needs: [ build ]

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v2

      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" >> ~/.ssh/id_rsa
          sudo apt-add-repository -y -u ppa:ansible/ansible
          sudo apt-get install -y rsync
          sudo apt-get install -y ansible

      - name: Deploy to Server
        run: |
          chmod 700 ci-scripts
          cd ci-scripts
          ansible-playbook -i "${{ secrets.REMOTE_HOST }}" -e "ansible_user=${{ secrets.REMOTE_USER }} \
            DB_LINK=${{ secrets.DB_LINK }} \
            
            MAIN_JWT_ACCESS_SECRET_KEY=${{ secrets.MAIN_JWT_ACCESS_SECRET_KEY }} \
            ADMIN_JWT_ACCESS_SECRET_KEY=${{ secrets.ADMIN_JWT_ACCESS_SECRET_KEY }} \
            
            SERVER_HOST=${{ secrets.SERVER_HOST }} \
            SERVER_PORT=${{ secrets.SERVER_PORT }} \
          
            PUSH_API_FILE=${{ secrets.PUSH_API_FILE }} \
            PUSH_API_FILE_DATA=${{ secrets.PUSH_API_FILE_DATA }} \
            PUSH_API_DATABASE=${{ secrets.PUSH_API_DATABASE }} \

            BASE_URL=${{ secrets.BASE_URL }} \
            RABBIT_URL=${{ secrets.RABBIT_URL }} \
          
            backend_bin=${{ secrets.backend_bin }} \
            PM2_SERVICE_NAME=${{ secrets.PM2_SERVICE_NAME }} \
            SRC_DIR=${{ github.workspace }}/" backend-update.yml;

  deploy-dev:
    environment: develop

    if: "github.ref == 'refs/heads/develop'"
    runs-on: ubuntu-18.04
    needs: [ build ]

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v2

      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" >> ~/.ssh/id_rsa
          sudo apt-add-repository -y -u ppa:ansible/ansible
          sudo apt-get install -y rsync
          sudo apt-get install -y ansible

      - name: Deploy to Server
        run: |
          chmod 700 ci-scripts
          cd ci-scripts
          ansible-playbook -i "${{ secrets.REMOTE_HOST }}" -e "ansible_user=${{ secrets.REMOTE_USER }} \
            DB_LINK=${{ secrets.DEV_DB_LINK }} \
            
            MAIN_JWT_ACCESS_SECRET_KEY=${{ secrets.DEV_MAIN_JWT_ACCESS_SECRET_KEY }} \
            ADMIN_JWT_ACCESS_SECRET_KEY=${{ secrets.DEV_ADMIN_JWT_ACCESS_SECRET_KEY }} \
          
            SERVER_HOST=${{ secrets.DEV_SERVER_HOST }} \
            SERVER_PORT=${{ secrets.DEV_SERVER_PORT }} \

            RABBIT_URL=${{ secrets.DEV_RABBIT_URL }} \
            BASE_URL=${{ secrets.DEV_BASE_URL }} \
          
            PUSH_API_FILE=${{ secrets.DEV_PUSH_API_FILE }} \
            PUSH_API_FILE_DATA=${{ secrets.DEV_PUSH_API_FILE_DATA }} \
            PUSH_API_DATABASE=${{ secrets.DEV_PUSH_API_DATABASE }} \
            
            backend_bin=${{ secrets.backend_bin }} \
            PM2_SERVICE_NAME=${{ secrets.PM2_SERVICE_NAME }} \
            SRC_DIR=${{ github.workspace }}/" backend-update.yml;

  deploy-TestNetwork:
    environment: TestNetwork

    if: "github.ref == 'refs/heads/TestNetwork'"
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v3

      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" >> ~/.ssh/id_rsa
          sudo apt-add-repository -y -u ppa:ansible/ansible
          sudo apt-get install -y rsync
          sudo apt-get install -y ansible

      - name: Deploy to Server
        run: |
          chmod 700 ci-scripts
          cd ci-scripts
          ansible-playbook -i "${{ secrets.REMOTE_HOST }}" -e "ansible_user=${{ secrets.REMOTE_USER }} \
            DB_LINK=${{ secrets.DB_LINK }} \
            
            MAIN_JWT_ACCESS_SECRET_KEY=${{ secrets.MAIN_JWT_ACCESS_SECRET_KEY }} \
            ADMIN_JWT_ACCESS_SECRET_KEY=${{ secrets.ADMIN_JWT_ACCESS_SECRET_KEY }} \
          
            SERVER_HOST=${{ secrets.SERVER_HOST }} \
            SERVER_PORT=${{ secrets.SERVER_PORT }} \

            RABBIT_URL=${{ secrets.RABBIT_URL }} \
            BASE_URL=${{ secrets.BASE_URL }} \
            
            backend_bin=${{ secrets.backend_bin }} \
            PM2_SERVICE_NAME=${{ secrets.PM2_SERVICE_NAME }} \
            SRC_DIR=${{ github.workspace }}/" backend-update.yml;
